### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by leewp14** [kevindierkx/laravel-domain-parser#13]
|    Q        |   A
|------------ | ------
| Version     | -- (Laravel 6.x)

### Question

Hi! I tried to install this package in my laravel project, however was unable to install. Could you help me look into this problem? I'm not sure if it is a misconfiguration on my side. 
As indicated above, I'm working on Laravel 6.x. 

Thanks!

![image](https://user-images.githubusercontent.com/17796518/103205057-a7a99280-4933-11eb-8acf-6bf85c033880.png)

**Comment by kevindierkx** [comment]
This is a common problem I face with composer, try specifying a specific version like: `composer require kevindierkx/laravel-domain-parser:^0.4`

**Comment by leewp14** [comment]
> This is a common problem I face with composer, try specifying a specific version like: `composer require kevindierkx/laravel-domain-parser:^0.4`

https://packagist.org/packages/bakame/laravel-domain-parser
https://packagist.org/users/kevindierkx/

Tried your suggested solution by specifying the version but didn't work. Then I came across this, seems like it could be the package name issue? As what I saw from packagist, it is under bakame but not you, although you are listed as maintainers, and the source url links to this repo. 

![Screenshot from 2021-01-06 03-01-52](https://user-images.githubusercontent.com/17796518/103687635-91eb3b80-4fcb-11eb-8d78-b5e3ff1c977d.png)

**Comment by kevindierkx** [comment]
@leewp14 Sorry, my mistake.. It should be `composer require bakame/laravel-domain-parser:^0.4`

I've noticed that I made the same mistake in the README 😆

**Comment by kevindierkx** [comment]
I've fixed the README. This package recently transfered ownership, since all the internal links got changed I've simply searched and replaced all occurences of `bakame/laravel-domain-parser`, this is of course not the case for the packagist registration which still points to the previous vendor. The name in the composer.json is leading for composer installs.

Nevertheless sometimes, when generally requiring a package, the dependency resolver doesn't quite match what I need. In those cases explicitly specifying a different version with `:^0.4` mostly fixes my problems.

@leewp14 I hope this fixed your problem!

**Comment by leewp14** [comment]
> I've fixed the README. This package recently transfered ownership, since all the internal links got changed I've simply searched and replaced all occurences of `bakame/laravel-domain-parser`, this is of course not the case for the packagist registration which still points to the previous vendor. The name in the composer.json is leading for composer installs.
> 
> Nevertheless sometimes, when generally requiring a package, the dependency resolver doesn't quite match what I need. In those cases explicitly specifying a different version with `:^0.4` mostly fixes my problems.
> 
> @leewp14 I hope this fixed your problem!

Yes, everything seems fine now. Thanks for the information and assistance!
